export const userConstants = {
    LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USER_LOGIN_FAILURE',

    LOGOUT: 'USERS_LOGOUT',

    REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USER_REGISTER_FAILURE',

    SET_USER_OPTIONS: 'SET_USER_OPTIONS',
}

export const postConstants = {
    POSTS_REQUEST: 'FETCH_POSTS_REQUEST',
    POSTS_SUCCESS: 'FETCH_POSTS_SUCCESS',
    POSTS_FAILURE: 'FETCH_POSTS_FAILURE',

    ADD_POST: 'ADD_POST',

    UPDATE_POST: 'UPDATE_POST',
    DELETE_POST: 'DELETE_POST',
}

export const CALL_API = 'Call API';
export const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE';